name: RatTranslate
version: @version@
main: io.github.ranolp.rattranslate.RatTranslateBukkit
authors: [Ranol_]
description: Universal translate plugin
commands:
  rattranslate:
    aliases: [rattr, rtr]
    description: "Enable or disable the translation."
  language:
    aliases: [lang]
    description: "Change the language or see the language list."
